### ISSUE TITLE
List of publications

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf.github.io#6]
We should have a tab "Publications" on https://cldf.clld.org

Structure:

- general papers
- catalogs
  - glottolog
    - paper
    - data
    - tools
  - concepticon
    - paper
    - data
    - tools
  - clts
    - paper
    - data
    - tools
- datasets (list communities on zenodo)
- tools
  - pycldf
  - pyigt
  - cldfbench
  - datasette-cldf

**Comment by LinguList** [comment]
I paste some evobib keys here, you can all access the bibtex via "https://digling.org/evobib/?bibtex=KEY".

* CLDF paper: Forkel2018a
* CLTS: Anderson2018
* Concepticon: List2016
* CLICS paper 2: List2018e

Now, some upcoming entries (will be in the next version of evobib):
* CLICS paper 3: Rzymski2020 (not yet in official evobib, have to wait for next update)
* Jackson2019

Versions of different datasets in evobib are as:

* Concepticon-2.1.0
* Concepticon (gives all versions, but the key is for the latest version)

This works also with glottolog and some other entries.

We need also quotes for the software parts (pyconcepticon, pyclts, etc.)

**Comment by LinguList** [comment]
The paper/data/tools is nice, by the way: we usually have only ONE paper for a given dataset (okay, CLICS has two), but we have many recent versions, etc. from the data, plus the tools. But we can avoid to give any "how you should quote if you use" recommendations, but instead just provide our Bibtex references, and people can decide themselves what they do.

**Comment by xrotwang** [comment]
Will open issues for individual additions.
