### ISSUE TITLE
Fixes for publications page

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf.github.io#8]
- [ ] missing "Publications" entry in top-menu on home page: https://cldf.clld.org/
- [ ] switch to full-width boxes on publications page (https://cldf.clld.org/publications.html), in particular because the boxes have very different content.

**Comment by chrzyki** [comment]
@xrotwang can you point me to the missing "Publications" top-menu? I'm afraid I can't see it, sorry.

**Comment by xrotwang** [comment]
Ah, sorry. Seems my browser cached the page before it was re-rendered on github.
